import * as readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import { configPaths, PRODUCT } from "./config.js";

export interface OnboardingResult {
  skipped: boolean;
  wroteUserConfig: boolean;
  focus: string;
  enabled: string[];
}

const STEPS = [
  "Welcome to dranix — multi-agent TUI orchestrator",
  "Config lives at ~/.config/dranix/agents.toml (user) then ./agents.toml (project wins)",
  "Adapters: mock (built-in), codex, claude-code, pi, oh-my-pi, kimi-code",
  "Soft-disable agents with enabled=false; /remove asks for confirm",
] as const;

/**
 * Skeleton sequential wizard. Safe to skip; writes a minimal user config when accepted.
 */
export async function runOnboarding(
  opts: { force?: boolean; cwd?: string } = {},
): Promise<OnboardingResult> {
  const paths = configPaths(opts.cwd);
  const already = existsSync(paths.user) || existsSync(paths.project);

  if (already && !opts.force) {
    return {
      skipped: true,
      wroteUserConfig: false,
      focus: "mock",
      enabled: ["mock"],
    };
  }

  const rl = readline.createInterface({ input, output });
  try {
    output.write("\n");
    for (let i = 0; i < STEPS.length; i++) {
      output.write(`  [${i + 1}/${STEPS.length}] ${STEPS[i]}\n`);
    }
    output.write("\n");

    const proceed = (
      await rl.question("Create a starter user config with mock agent? [Y/n] ")
    )
      .trim()
      .toLowerCase();

    if (proceed === "n" || proceed === "no") {
      return {
        skipped: true,
        wroteUserConfig: false,
        focus: "mock",
        enabled: ["mock"],
      };
    }

    const focusRaw = await rl.question("Default focus agent id [mock]: ");
    const focus = focusRaw.trim() || "mock";

    const toml = `# Generated by dranix onboarding
visibility = "${PRODUCT.visibility}"
on_quit = "${PRODUCT.on_quit}"
io = "${PRODUCT.io}"

[defaults]
focus = "${focus}"
max_timeline = 200
max_chars = 4000

[[agents]]
id = "mock"
name = "Mock Echo"
adapter = "mock"
enabled = true
command = "mock"
`;

    mkdirSync(dirname(paths.user), { recursive: true });
    writeFileSync(paths.user, toml, "utf8");
    output.write(`Wrote ${paths.user}\n`);

    return {
      skipped: false,
      wroteUserConfig: true,
      focus,
      enabled: ["mock"],
    };
  } finally {
    rl.close();
  }
}

export { STEPS as ONBOARDING_STEPS };
